### ISSUE TITLE
"imageo" should be "imageio" in the instructions for Devangari example

### ISSUE THREAD

**Issue by shradej1** [ICERM-TRIPODS-Top-ML/Top-ML#1]
There is no pip / conda package called "imageo".  The wiki should mention "imageio".

**Comment by henryadams** [comment]
Hi Joshua,
Great, thank you! I made this change in the wiki. Please let us know if you have any other suggestions. I hope to be adding some more functionality to the code and wiki tomorrow.
Best, Henry
